"""empty message

Revision ID: b411b32b2126
Revises: 
Create Date: 2019-03-29 13:43:44.836471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b411b32b2126'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('saldo_admin', sa.Integer(), nullable=True))
    op.add_column('booking', sa.Column('saldo_mentor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'saldo_mentor')
    op.drop_column('booking', 'saldo_admin')
    # ### end Alembic commands ###
