"""empty message

Revision ID: c7a60b9c1d01
Revises: b7f3d38ec501
Create Date: 2019-03-31 16:01:02.485938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a60b9c1d01'
down_revision = 'b7f3d38ec501'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('client_id', table_name='blocked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('client_id', 'blocked', ['client_id'], unique=True)
    # ### end Alembic commands ###
